argument_specs:
  main:
    options:

      alternatives__alternatives:
        type: 'list'
        elements: 'dict'
        required: true
        description: >-
          List of `update-alternatives` entries to manage.
        options:

          link:
            type: 'str'
            required: false
            description: >-
              Path to the symlink that should point at the real
              executable. Mandatory on Red Hat-family. On Debian only
              required when the alternative `name` is unknown to the
              system.

          name:
            type: 'str'
            required: true
            description: 'The generic name of the alternative.'

          path:
            type: 'str'
            required: false
            description: 'Path to the real executable.'

          priority:
            type: 'int'
            required: false
            description: >-
              Priority weight for `auto` mode (default fallback for
              creation: 50).

          state:
            type: 'str'
            required: false
            default: 'selected'
            choices:
              - 'absent'
              - 'auto'
              - 'present'
              - 'selected'
            description: >-
              `selected` (default), `present`, `auto`, or `absent`.
