argument_specs:
  main:
    options:

      lvm__lvs__group_var:
        type: 'list'
        elements: 'dict'
        required: false
        default: []
        description: >-
          List of logical volumes to manage. Group-level override. See
          README for the full subkey schema (`name`, `vg`, `size`,
          `filesystem`, `mount_path`, ...).

      lvm__lvs__host_var:
        type: 'list'
        elements: 'dict'
        required: false
        default: []
        description: 'List of logical volumes to manage. Host-level override.'

      lvm__vgs__group_var:
        type: 'list'
        elements: 'dict'
        required: false
        default: []
        description: >-
          List of volume groups to manage. Group-level override. See
          README for the full subkey schema (`name`, `pvs`, `growpart`,
          ...).

      lvm__vgs__host_var:
        type: 'list'
        elements: 'dict'
        required: false
        default: []
        description: 'List of volume groups to manage. Host-level override.'
