__duplicity__python_venv__venvs__dependent_var:
  RedHat8:
    - name: 'duplicity'
      packages:
        - 'duplicity'
        # If we add these, we get "SetuptoolsDeprecationWarning: Invalid dash-separated options",
        # and current versions of duplicity (now) installs these as well:
        # - 'python-keystoneclient'
        # - 'python-swiftclient'
      package_requirements:
        - 'gcc'
        - 'librsync-devel'
        - 'python3.11-devel'
      python_executable: 'python3.11'
      exposed_binaries:
        - 'duplicity'
  RedHat9:
    - name: 'duplicity'
      packages:
        - 'duplicity'
        # If we add these, we get "SetuptoolsDeprecationWarning: Invalid dash-separated options",
        # and current versions of duplicity (now) installs these as well:
        # - 'python-keystoneclient'
        # - 'python-swiftclient'
      package_requirements:
        - 'gcc'
        - 'librsync-devel'
        - 'python3.11-devel'
      python_executable: 'python3.11'
      exposed_binaries:
        - 'duplicity'
  RedHat10:
    - name: 'duplicity'
      packages:
        - 'duplicity'
        # If we add these, we get "SetuptoolsDeprecationWarning: Invalid dash-separated options",
        # and current versions of duplicity (now) installs these as well:
        # - 'python-keystoneclient'
        # - 'python-swiftclient'
      package_requirements:
        - 'gcc'
        - 'librsync-devel'
        - 'python3.13-devel'
      python_executable: 'python3.13'
      exposed_binaries:
        - 'duplicity'
duplicity__python_venv__venvs__dependent_var: '{{
    __duplicity__python_venv__venvs__dependent_var
    | linuxfabrik.lfops.platform_select(ansible_facts)
  }}'
