- block:

  - name: 'Install aide'
    ansible.builtin.package:
      name:
        - 'aide'
      state: 'present'
    retries: 3 # ride out a brief outage of the package repository
    delay: 10

  tags:
    - 'aide'
