nextcloud__php__fpm_service_name: 'php{{ php__installed_version }}-fpm'
nextcloud__php__modules__dependent_var:
  - { name: 'php-bcmath', state: 'present' }
  - { name: 'php-gd', state: 'present' }
  - { name: 'php-gmp', state: 'present' }
  - { name: 'php-imap', state: 'present' }
  - { name: 'php-imagick', state: 'present' }
  - { name: 'php-intl', state: 'present' }
  - { name: 'php-json', state: 'present' }
  - { name: 'php-ldap', state: 'present' }
  - { name: 'php-mbstring', state: 'present' }
  - { name: 'php-memcached', state: 'present' }
  - { name: 'php-mysqlnd', state: 'present' }
  - { name: 'php-opcache', state: 'present' }
  - { name: 'php-apcu', state: 'present' }
  - { name: 'php-xml', state: 'present' }
  - { name: 'php-redis', state: 'present' }
  - { name: 'php-smbclient', state: 'present' }
  - { name: 'php-zip', state: 'present' }
nextcloud__php__webserver_group: '{{ php__webserver_group }}'
nextcloud__php__webserver_user: '{{ php__webserver_user }}'
nextcloud__system_packages:
  - 'bzip2'
  - 'jq'
  - 'ldap-utils'
  - 'smbclient'
