- block:

  - name: 'Set platform/version specific variables'
    ansible.builtin.import_role:
      name: 'shared'
      tasks_from: 'platform-variables.yml'

  - name: 'Install {{ mailx__package }} package'
    ansible.builtin.package:
      name: '{{ mailx__package }}'
      state: 'present'

  - name: 'Deploy bash wrapper script that makes sending mail easier to /root/send-mail'
    ansible.builtin.template:
      backup: true
      dest: '/root/send-mail'
      mode: 0o755
      owner: 'root'
      src: 'root/send-mail.j2'

  tags:
    - 'mailx'
