- name: 'sshd: sshd -t; reload sshd'
  ansible.builtin.command: 'sshd -t'
  notify:
    - 'sshd: reload sshd'

- name: 'sshd: reload sshd'
  ansible.builtin.service:
    name: 'sshd'
    state: 'reloaded'
