__php__conf_dest:
  - '/etc/php.d/z00-linuxfabrik.ini'
__php__fpm_opcache_path: '/var/lib/php/opcache'
__php__fpm_pools_path: '/etc/php-fpm.d'
__php__fpm_runtime_path: '/run/php-fpm'
__php__fpm_service_name: 'php-fpm'
__php__fpm_session_path: '/var/lib/php/session'
