- block:

  - name: 'Install postfix, mailutils, sasl2-bin, libsasl2-2 and libsasl2-modules on Debian 12'
    ansible.builtin.apt:
      pkg:
        - 'postfix'
        - 'mailutils'
        - 'sasl2-bin'
        - 'libsasl2-2'
        - 'libsasl2-modules'
      update_cache: true
      state: 'present'
    retries: 3 # ride out a brief outage of the package repository
    delay: 10
    environment:
      DEBIAN_FRONTEND: 'noninteractive'

  tags:
    - 'postfix'
