- block:

  - name: 'Install open-vm-tools'
    ansible.builtin.package:
      name:
        - 'open-vm-tools'
      state: 'present'

  tags:
    - 'open_vm_tools'


- block:

  - name: 'systemctl {{ open_vm_tools__service_enabled | bool | ternary("enable", "disable") }} vmtoolsd.service'
    ansible.builtin.service:
      name: 'vmtoolsd.service'
      enabled: '{{ open_vm_tools__service_enabled | bool }}'

  - name: 'systemctl {{ open_vm_tools__service_state | regex_replace("p?ed$", "") }} vmtoolsd.service'
    ansible.builtin.service:
      name: 'vmtoolsd.service'
      state: '{{ open_vm_tools__service_state }}'

  tags:
    - 'open_vm_tools'
    - 'open_vm_tools:state'
