apache_httpd__conf_server_admin: 'root@localhost'

librenms__database_login:
  username: 'librenms'
  password: 'linuxfabrik'
librenms__fqdn: 'librenms.example.com'

mariadb_server__admin_user:
  username: 'mariadb-admin'
  password: 'linuxfabrik'

repo_mariadb__version: '11.4'

repo_remi__enabled_php_version: '8.4'
