systems_under_test:
  hosts:
    debian11-container:
    debian12-container:
    debian13-container:
    rocky8-container:
    rocky9-container:
    rocky10-container:
    ubuntu2004-container:
    ubuntu2204-container:
    ubuntu2404-container:
