#!/bin/bash

# $1: subject, $2: body, $3: recipient, $4: attachment
if [ -z "$1" ]; then
	echo "$0 subject body recipients [attachment]"
	exit
fi
if [ -z "$4" ]; then
	echo $2 | mail -s "$1" $3
else
	echo $2 | mail -s "$1" -a "$4" $3
fi
