lfops_setup_basic:
  hosts:
    debian11-vm:
    debian12-vm:
    debian13-vm:
    rocky8-vm:
    rocky9-vm:
    rocky10-vm:
    ubuntu2004-vm:
    ubuntu2204-vm:
    ubuntu2404-vm:

systems_under_test:
  hosts:
    debian11-vm:
    debian12-vm:
    debian13-vm:
    rocky8-vm:
    rocky9-vm:
    rocky10-vm:
    ubuntu2004-vm:
    ubuntu2204-vm:
    ubuntu2404-vm:
