- block:

  - name: 'Deploy /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el{{ ansible_facts["distribution_major_version"] }}'
    ansible.builtin.copy:
      src: '{{ ansible_facts["os_family"] }}{{ ansible_facts["distribution_major_version"] }}/etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el{{ ansible_facts["distribution_major_version"] }}'
      dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el{{ ansible_facts["distribution_major_version"] }}'
      owner: 'root'
      group: 'root'
      mode: 0o644

  tags:
    - 'repo_remi'


# note: the remi repo still uses modularity with RHEL10 even though `modularity is deprecated, and functionality will be removed in a future release of DNF5.` have a look at https://github.com/remicollet/remirepo/issues/265#issuecomment-2298206332
- block:

  - name: 'dnf -y module reset php'
    ansible.builtin.command: 'dnf -y module reset php'
    register: '__repo_remi__dnf_module_reset_php_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_reset_php_result["stdout"]'

  - name: 'dnf -y module enable php:remi-{{ repo_remi__enabled_php_version }}'
    ansible.builtin.command: 'dnf -y module enable php:remi-{{ repo_remi__enabled_php_version }}'
    register: '__repo_remi__dnf_module_enable_php_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_enable_php_result["stdout"]'

  # block
  when: 'repo_remi__enabled_php_version is defined and repo_remi__enabled_php_version | length > 0'
  tags:
    - 'repo_remi'


- block:

  - name: 'dnf -y module reset composer'
    ansible.builtin.command: 'dnf -y module reset composer'
    register: '__repo_remi__dnf_module_reset_composer_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_reset_composer_result["stdout"]'

  - name: 'dnf -y module enable composer'
    ansible.builtin.command: 'dnf -y module enable composer'
    register: '__repo_remi__dnf_module_enable_composer_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_enable_composer_result["stdout"]'

  # block
  when: 'repo_remi__enabled_php_version is defined and repo_remi__enabled_php_version | length > 0'
  tags:
    - 'repo_remi'


- block:

  - name: 'dnf -y module reset redis'
    ansible.builtin.command: 'dnf -y module reset redis'
    register: '__repo_remi__dnf_module_reset_redis_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_reset_redis_result["stdout"]'

  - name: 'dnf -y module enable redis:remi-{{ repo_remi__enabled_redis_version }}'
    ansible.builtin.command: 'dnf -y module enable redis:remi-{{ repo_remi__enabled_redis_version }}'
    register: '__repo_remi__dnf_module_enable_redis_result'
    changed_when: '"Nothing to do" not in __repo_remi__dnf_module_enable_redis_result["stdout"]'

  # block
  when: 'repo_remi__enabled_redis_version is defined and repo_remi__enabled_redis_version | length > 0'
  tags:
    - 'repo_remi'
