- name: 'clamav: restart clamd'
  ansible.builtin.service:
    name: '{{ __clamav__clamd_service }}'
    state: 'restarted'
  when:
    - 'clamav__clamd_service_enabled'

- name: 'clamav: restart clamav-clamonacc'
  ansible.builtin.service:
    name: 'clamav-clamonacc'
    state: 'restarted'
  when:
    - 'clamav__clamonacc_service_enabled'
