argument_specs:
  main:
    options:

      icingaweb2_module_businessprocess__url:
        type: 'str'
        required: false
        description: >-
          The URL from which the module tarball is downloaded.
          Defaults to
          `https://github.com/Icinga/icingaweb2-module-businessprocess/archive/{{ icingaweb2_module_businessprocess__version }}.tar.gz`.

      icingaweb2_module_businessprocess__version:
        type: 'str'
        required: true
        description: >-
          The module version to install. Possible options:
          https://github.com/Icinga/icingaweb2-module-businessprocess/releases.
