- name: 'Verify apps are not installed'
  hosts: 'systems_under_test'
  gather_facts: false
  tasks:
    - name: 'Gather the package facts'
      ansible.builtin.package_facts:  # yamllint disable-line rule:empty-values

    - name: 'Assert that less is not installed'
      ansible.builtin.assert:
        that: '"less" not in ansible_facts["packages"]'
