ansible_connection: 'containers.podman.podman'
ansible_host: 'rocky9-container'

container_command: '/usr/sbin/init'
container_image: 'docker.io/rockylinux/rockylinux:9-ubi-init'
container_privileged: false
container_systemd: true
