ansible_connection: 'containers.podman.podman'
ansible_host: 'rocky9-container'

molecule__container_command: '/usr/sbin/init'
molecule__container_image: 'docker.io/rockylinux/rockylinux:9-ubi-init'
molecule__container_systemd: true
