- name: 'Install libuser'
  ansible.builtin.package:
    name:
      - 'libuser'
    state: 'present'
  retries: 3 # ride out a brief outage of the package repository
  delay: 10
  tags:
    - 'login'
