- block:

  - name: 'Install qemu-guest-agent'
    ansible.builtin.package:
      name:
        - 'qemu-guest-agent'
      state: 'present'

  tags:
    - 'qemu_guest_agent'


- block:

  - name: 'systemctl {{ qemu_guest_agent__service_enabled | bool | ternary("enable", "disable") }} qemu-guest-agent.service'
    ansible.builtin.service:
      name: 'qemu-guest-agent.service'
      enabled: '{{ qemu_guest_agent__service_enabled | bool }}'

  - name: 'systemctl {{ qemu_guest_agent__service_state }} qemu-guest-agent.service'
    ansible.builtin.service:
      name: 'qemu-guest-agent.service'
      state: '{{ qemu_guest_agent__service_state }}'

  tags:
    - 'qemu_guest_agent'
    - 'qemu_guest_agent:state'
