code_package_name: 'code-brand'
collabora__spell_packages:
  - 'hunspell'
  - 'libmythes-1.2-0'
collabora__language_packages__role_var:
  # de
  - { name: 'collaboraoffice-dict-de', state: 'present' }
  - { name: 'collaboraofficebasis-de', state: 'present' }
  - { name: 'mythes-de', state: 'present' }
  - { name: 'hunspell-de-de', state: 'present' }
  # en
  - { name: 'collaboraoffice-dict-en', state: 'present' }
  - { name: 'collaboraofficebasis-en-gb', state: 'present' }
  - { name: 'collaboraofficebasis-en-us', state: 'present' }
  - { name: 'mythes-en-us', state: 'present' }
  - { name: 'hunspell-en-gb', state: 'present' }
  - { name: 'hunspell-en-us', state: 'present' }
  # fr
  - { name: 'collaboraoffice-dict-fr', state: 'present' }
  - { name: 'collaboraofficebasis-fr', state: 'present' }
  - { name: 'mythes-fr', state: 'present' }
  - { name: 'hunspell-fr', state: 'present' }
  # it
  - { name: 'collaboraoffice-dict-it', state: 'present' }
  - { name: 'collaboraofficebasis-it', state: 'present' }
  - { name: 'mythes-it', state: 'present' }
  - { name: 'hunspell-it', state: 'present' }
