code_package_name: 'CODE-brand'
collabora__spell_packages:
  - 'hunspell'
  - 'mythes'
collabora__language_packages__role_var:
  - { name: 'collaboraoffice-dict-de', state: 'present' }
  - { name: 'collaboraofficebasis-de', state: 'present' }
  - { name: 'mythes-de', state: 'present' }
  - { name: 'hunspell-de-de', state: 'present' }
  - { name: 'collaboraoffice-dict-en', state: 'present' }
  - { name: 'collaboraofficebasis-en-gb', state: 'present' }
  - { name: 'collaboraofficebasis-en-us', state: 'present' }
  - { name: 'mythes-en-us', state: 'present' }
  - { name: 'hunspell-en-gb', state: 'present' }
  - { name: 'hunspell-en-us', state: 'present' }
