- block:

  - name: 'Run OS-specific setup'
    ansible.builtin.include_tasks:
      file: '{{ ansible_facts["os_family"] }}.yml'

  - name: 'Remove rpmnew / rpmsave (and Debian equivalents)'
    ansible.builtin.include_role:
      name: 'shared'
      tasks_from: 'remove-rpmnew-rpmsave.yml'
    vars:
      shared__remove_rpmnew_rpmsave_config_file: '/etc/yum.repos.d/Collabora.repo'

  tags:
    - 'repo_collabora_code'
