#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

"""Unit tests for the bitwarden_item module.

`diff_and_update` is a plain function tested in isolation. The main()
behavior (check_mode must not write, a None password must not overwrite
an existing one) is tested with a fake Bitwarden client and the shared
ansible module harness. The collection import is wired up by
tests/conftest.py.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

import copy
import unittest
import unittest.mock

import ansible_harness

from ansible_collections.linuxfabrik.lfops.plugins.modules import bitwarden_item as mod
from ansible_collections.linuxfabrik.lfops.plugins.modules.bitwarden_item import diff_and_update


class TestDiffAndUpdate(unittest.TestCase):

    def test_takes_over_id(self):
        current = {'id': 'abc', 'name': 'x'}
        target = {'name': 'x'}
        changed, updated = diff_and_update(current, target)
        self.assertEqual(updated['id'], 'abc')

    def test_no_change_when_equal(self):
        current = {'id': 'abc', 'name': 'x', 'notes': 'n'}
        target = {'name': 'x', 'notes': 'n'}
        changed, _ = diff_and_update(current, target)
        self.assertFalse(changed)

    def test_change_detected_on_differing_value(self):
        current = {'id': 'abc', 'name': 'x', 'notes': 'old'}
        target = {'name': 'x', 'notes': 'new'}
        changed, _ = diff_and_update(current, target)
        self.assertTrue(changed)

    def test_falsy_vs_falsy_is_not_a_change(self):
        # None vs empty list / empty string must not count as a change
        current = {'id': 'abc', 'collectionIds': None, 'notes': ''}
        target = {'collectionIds': [], 'notes': None}
        changed, _ = diff_and_update(current, target)
        self.assertFalse(changed)

    def test_nested_dict_change_detected(self):
        current = {'id': 'abc', 'login': {'username': 'old', 'totp': ''}}
        target = {'login': {'username': 'new', 'totp': ''}}
        changed, _ = diff_and_update(current, target)
        self.assertTrue(changed)

    def test_nested_dict_no_change(self):
        current = {'id': 'abc', 'login': {'username': 'same', 'totp': ''}}
        target = {'login': {'username': 'same', 'totp': ''}}
        changed, _ = diff_and_update(current, target)
        self.assertFalse(changed)


_EXISTING_ITEM = {
    'id': 'abc',
    'name': 'host - db',
    'login': {'username': 'dba', 'password': 'linuxfabrik-existing', 'totp': '', 'uris': []},
    'notes': 'Generated by Ansible.',
    'organizationId': None,
    'collectionIds': None,
    'folderId': None,
}


class _FakeBitwarden:
    """Stand-in for the Bitwarden client; records writes instead of doing them."""

    items = []
    edited = []
    created = []

    def __init__(self, *args, **kwargs):
        pass

    @property
    def is_unlocked(self):
        return True

    def sync(self, *args, **kwargs):
        pass

    def get_items(self, *args, **kwargs):
        return [copy.deepcopy(i) for i in type(self).items]

    def get_item_by_id(self, item_id):
        return None

    def get_template_item_login_uri(self, uris):
        return list(uris or [])

    def get_template_item_login(self, username=None, password=None, login_uris=None):
        return {'username': username, 'password': password, 'totp': '', 'uris': login_uris or []}

    def get_template_item(self, name, login=None, notes=None, organization_id=None,
                          collection_ids=None, folder_id=None):
        return {
            'name': name, 'login': login, 'notes': notes,
            'organizationId': organization_id, 'collectionIds': collection_ids,
            'folderId': folder_id,
        }

    @staticmethod
    def get_pretty_name(name, hostname=None, purpose=None):
        return name or hostname

    def edit_item(self, item, item_id):
        type(self).edited.append((copy.deepcopy(item), item_id))
        result = copy.deepcopy(item)
        result['id'] = item_id
        return result

    def create_item(self, item):
        type(self).created.append(copy.deepcopy(item))
        result = copy.deepcopy(item)
        result['id'] = 'new-id'
        return result


class TestMain(unittest.TestCase):

    def setUp(self):
        _FakeBitwarden.items = []
        _FakeBitwarden.edited = []
        _FakeBitwarden.created = []
        self._patchers = [
            unittest.mock.patch.object(mod, 'Bitwarden', _FakeBitwarden),
            ansible_harness.patch_module(),
        ]
        for p in self._patchers:
            p.start()

    def tearDown(self):
        for p in reversed(self._patchers):
            p.stop()

    def _run(self, args):
        ansible_harness.set_module_args(args)
        try:
            mod.run_module()
        except ansible_harness.AnsibleExitJson as exc:
            return exc.args[0]
        raise AssertionError('module did not call exit_json')

    def test_check_mode_create_does_not_write(self):
        _FakeBitwarden.items = []  # nothing exists -> would create
        result = self._run({
            'name': 'host - db', 'username': 'dba', 'password': 'linuxfabrik-new',
            '_ansible_check_mode': True,
        })
        self.assertTrue(result['changed'])
        self.assertEqual(_FakeBitwarden.created, [])  # no write in check mode

    def test_check_mode_edit_does_not_write(self):
        _FakeBitwarden.items = [_EXISTING_ITEM]
        result = self._run({
            'name': 'host - db', 'username': 'dba', 'password': 'a-different-password',
            '_ansible_check_mode': True,
        })
        self.assertTrue(result['changed'])
        self.assertEqual(_FakeBitwarden.edited, [])  # no write in check mode

    def test_none_password_does_not_overwrite(self):
        _FakeBitwarden.items = [_EXISTING_ITEM]
        # password omitted entirely -> must preserve the existing one, no change
        result = self._run({'name': 'host - db', 'username': 'dba'})
        self.assertFalse(result['changed'])
        self.assertEqual(_FakeBitwarden.edited, [])
        self.assertEqual(result['password'], 'linuxfabrik-existing')

    def test_changed_password_writes_when_not_check_mode(self):
        _FakeBitwarden.items = [_EXISTING_ITEM]
        result = self._run({
            'name': 'host - db', 'username': 'dba', 'password': 'a-different-password',
        })
        self.assertTrue(result['changed'])
        self.assertEqual(len(_FakeBitwarden.edited), 1)


if __name__ == '__main__':
    unittest.main()
