- name: 'Destroy container instances'
  hosts: 'systems_under_test'
  gather_facts: false
  tasks:

    - name: 'Kill container if running'
      containers.podman.podman_container:
        name: '{{ inventory_hostname }}'
        state: 'absent'
        timeout: 2
      delegate_to: 'localhost'
