- name: 'Verify apps are installed'
  hosts: 'systems_under_test'
  gather_facts: false
  tasks:
    - name: 'Gather the package facts'
      ansible.builtin.package_facts:  # yamllint disable-line rule:empty-values

    - name: 'Assert that zsh is installed'
      ansible.builtin.assert:
        that: '"zsh" in ansible_facts["packages"]'
