- name: 'Playbook linuxfabrik.lfops.icingaweb2_module_pdfexport'
  hosts:
    - 'lfops_icingaweb2_module_pdfexport'

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'


  roles:

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'not icingaweb2_module_pdfexport__skip_repo_epel | d(false) | bool'

    - role: 'linuxfabrik.lfops.repo_google_chrome'
      when:
        - 'not icingaweb2_module_pdfexport__skip_repo_google_chrome | d(false) | bool'

    - role: 'linuxfabrik.lfops.google_chrome'
      when:
        - 'not icingaweb2_module_pdfexport__skip_google_chrome | d(false) | bool'

    - role: 'linuxfabrik.lfops.icingaweb2_module_pdfexport'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'
