- name: 'Playbook linuxfabrik.lfops.icingaweb2_module_pdfexport'
  hosts:
    - 'lfops_icingaweb2_module_pdfexport'

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'

    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'global-variables.yml'
      tags:
        - 'always'


  roles:

    - role: 'linuxfabrik.lfops.repo_baseos'
      repo_baseos__crb_repo_enabled__dependent_var: '{{
          repo_epel__repo_baseos__crb_repo_enabled__dependent_var
        }}'
      when:
        - 'ansible_facts["distribution"] == "Rocky" and ansible_facts["distribution_major_version"] | int >= 9'
        - 'not icingaweb2_module_pdfexport__skip_repo_baseos | d(false)'

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'ansible_facts["os_family"] == "RedHat"'
        - 'not icingaweb2_module_pdfexport__skip_repo_epel | d(false) | bool'

    - role: 'linuxfabrik.lfops.chromium_headless'
      when:
        - 'not icingaweb2_module_pdfexport__skip_chromium_headless | d(false) | bool'

    - role: 'linuxfabrik.lfops.icingaweb2_module_pdfexport'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'

    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'print-messages.yml'
      tags:
        - 'always'
