- name: 'Playbook linuxfabrik.lfops.influxdb'
  hosts:
    - 'lfops_influxdb'

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'


  roles:

    - role: 'linuxfabrik.lfops.repo_influxdb'

      # On Rocky 9+ the EPEL and CRB Repo need to be enabled to install python3-virtualenv
    - role: 'linuxfabrik.lfops.repo_baseos'
      repo_baseos__crb_repo_enabled__dependent_var: '{{
          repo_epel__repo_baseos__crb_repo_enabled__dependent_var
        }}'
      when:
        - 'ansible_facts["distribution"] == "Rocky" and ansible_facts["distribution_major_version"] | int >= 9'
        - 'not influxdb__skip_repo_baseos | d(false)'

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'ansible_facts["os_family"] == "RedHat"'
        - 'ansible_facts["distribution_major_version"] | int >= 9'
        - 'not influxdb__skip_repo_epel | d(false)'

    - role: 'linuxfabrik.lfops.python_venv'
      python_venv__venvs__dependent_var: '{{
          influxdb__python_venv__venvs__dependent_var
        }}'
      when:
        - 'not influxdb__skip_python_venv | d(false)'
    - role: 'linuxfabrik.lfops.influxdb'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'
