- name: 'Playbook linuxfabrik.lfops.lynis'
  hosts:
    - 'lfops_lynis'
  force_handlers: true

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'

    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'global-variables.yml'
      tags:
        - 'always'


  roles:

    # lynis is packaged in EPEL on the Red Hat family, in the distribution repositories elsewhere.
    # EPEL packages depend on CRB, which is not enabled by default on Rocky 9+.
    - role: 'linuxfabrik.lfops.repo_baseos'
      repo_baseos__crb_repo_enabled__dependent_var: '{{
          repo_epel__repo_baseos__crb_repo_enabled__dependent_var
        }}'
      when:
        - 'ansible_facts["distribution"] == "Rocky" and ansible_facts["distribution_major_version"] | int >= 9'
        - 'not lynis__skip_repo_baseos | d(false)'

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'ansible_facts["os_family"] == "RedHat"'
        - 'ansible_facts["distribution"] != "Fedora"'
        - 'not lynis__skip_repo_epel | d(false)'

    - role: 'linuxfabrik.lfops.lynis'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'

    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'print-messages.yml'
      tags:
        - 'always'
