- name: 'Playbook linuxfabrik.lfops.mongodb'
  hosts:
    - 'lfops_mongodb'

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'


  roles:

    - role: 'linuxfabrik.lfops.kernel_settings'
      kernel_settings__sysctl__dependent_var: '{{ mongodb__kernel_settings__sysctl__dependent_var | d([]) }}'
      kernel_settings__transparent_hugepages__dependent_var: "{{ mongodb__kernel_settings__transparent_hugepages__dependent_var | d('') }}"
      when:
        - 'not mongodb__skip_kernel_settings | d(false)'

      # On Rocky 9+ the EPEL and CRB Repo need to be enabled to install python3-virtualenv
    - role: 'linuxfabrik.lfops.repo_baseos'
      repo_baseos__crb_repo_enabled__dependent_var: '{{
          repo_epel__repo_baseos__crb_repo_enabled__dependent_var
        }}'
      when:
        - 'ansible_facts["distribution"] == "Rocky" and ansible_facts["distribution_major_version"] | int >= 9'
        - 'not mongodb__skip_repo_baseos | d(false)'

    - role: 'linuxfabrik.lfops.repo_epel'
      when:
        - 'ansible_facts["os_family"] == "RedHat"'
        - 'ansible_facts["distribution_major_version"] | int >= 9'
        - 'not mongodb__skip_repo_epel | d(false)'

    - role: 'linuxfabrik.lfops.python_venv'
      python_venv__venvs__dependent_var: '{{
          mongodb__python_venv__venvs__dependent_var
        }}'
      when:
        - 'not mongodb__skip_python_venv | d(false)'

    - role: 'linuxfabrik.lfops.repo_mongodb'
      when:
        - 'not mongodb__skip_repo_mongodb | default(false)'

    - role: 'linuxfabrik.lfops.mongodb'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'
