- name: 'Playbook linuxfabrik.lfops.rl9_cis'
  hosts: 
    - 'lfops_rl9_cis'

  pre_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-start.yml'
      tags:
        - 'always'


  roles:
    - role: 'linuxfabrik.lfops.aide'


  post_tasks:
    - ansible.builtin.import_role:
        name: 'shared'
        tasks_from: 'log-end.yml'
      tags:
        - 'always'
