#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
module: bitwarden_item

short_description: Create, update or fetch a Bitwarden login item

description:
    - Looks up a Bitwarden login item by name (and optional username, folder, collection and organization), or directly by Bitwarden item ID, and creates or updates it as needed to match the given parameters.
    - When the item does not yet exist, it is created with the supplied values. When it exists but differs from the supplied values, it is updated in place. When it already matches, no API call is made and the module reports C(changed=false).
    - When I(id) is set, only the lookup-by-ID path is used and all other search filters are ignored. The module fails if the ID does not exist - IDs are never auto-created.
    - When the lookup is by name and matches more than one item, the module fails because it cannot decide which item to operate on.
    - When I(name) is omitted, a title is generated automatically as C(hostname - purpose) (e.g. C(appsrv01 - MariaDB)) or just C(hostname) when no purpose is given.
    - On success, the module returns the full Bitwarden item object. C(username) and C(password) are additionally lifted to the top level so they can be addressed without going through the C(login) sub-dictionary.
    - Items are read from a local on-disk cache backed by C(bw serve). A cached C(bw sync) is performed at most every 60 seconds, so consecutive calls in the same play do not hammer the API.

notes:
    - Only login items (Bitwarden type 1) are managed. Cards, secure notes and identities are out of scope.
    - TOTP secrets are not managed; the C(totp) field is set to an empty string on creation.
    - I(uris) replaces the URI list on every run. Omitting it on an existing item causes the URI list to be cleared.
    - I(password) defaults to C(None), which leaves the password unmanaged - a new item is created without one, and an existing item keeps its current password. Use the C(bitwarden_item) lookup plugin to generate one.
    - Attachments are matched by basename only; this module assumes that an attachment with the same basename has the same content. Pre-existing attachments are kept; only missing ones are uploaded.
    - Organization, collection and folder IDs can be copied from the URL in the Bitwarden web vault.
    - The cache file lives in C($XDG_RUNTIME_DIR) (falling back to C(/tmp)) and is shared across this module and the C(bitwarden_item) lookup within the same controller session.

requirements:
    - Bitwarden CLI C(bw) version v2022.9.0 or newer. See U(https://bitwarden.com/help/article/cli/) for installation instructions.
    - You must be logged in and unlocked (C(bw login) followed by C(bw unlock)), and have the local API running, e.g. C(bw serve --hostname 127.0.0.1 --port 8087). The module connects to C(127.0.0.1:8087) by default.

author:
    - Linuxfabrik GmbH, Zurich, Switzerland, https://www.linuxfabrik.ch

version_added: "1.0.0"

options:
    attachments:
        description:
            - List of local file paths to upload as attachments. The basename of each path is used as the attachment name in Bitwarden.
            - Bitwarden allows duplicate attachment names, but this module does not, and fails if two paths share the same basename.
            - Existing attachments with the same basename are assumed to have the same content and are not re-uploaded.
        required: False
        type: list
    collection_id:
        description: Bitwarden collection ID the item belongs to. Used both as a search filter and, if the item has to be created, as the target collection.
        required: False
        type: str
    folder_id:
        description: Bitwarden folder ID the item belongs to. Used both as a search filter and, if the item has to be created, as the target folder.
        required: False
        type: str
    hostname:
        description: Hostname the password belongs to. Used to generate the item name when I(name) is not given.
        required: False
        type: str
    id:
        description: Operate on an existing item by its Bitwarden item ID. When set, all other search filters are ignored. The module fails if the ID does not exist (no auto-creation).
        required: False
        type: str
    name:
        description: Explicit name/title of the item. When set, disables automatic name generation from I(hostname) and I(purpose).
        required: False
        type: str
    notes:
        description: Notes to set on the item. Bitwarden limits notes to 10000 characters. Updates on existing items overwrite previous notes.
        default: 'Generated by Ansible.'
        required: False
        type: str
    organization_id:
        description: Bitwarden organization ID the item belongs to. Used both as a search filter and, if the item has to be created, as the target organization.
        required: False
        type: str
    password:
        description: Password to set on the login item. C(None) (the default) leaves the password unmanaged - a new item gets no password and an existing item keeps its current one. Any non-C(None) value is written on every run.
        required: False
        type: str
    purpose:
        description: What the password is for (e.g. C(MariaDB), C(Rocky)). Combined with I(hostname) to build the item name when I(name) is not given.
        required: False
        type: str
    uris:
        description: List of URIs to set on the login item. The URI list is replaced on every run; omit only when you want the item to have no URIs.
        required: False
        type: list
    username:
        description: Username to set on the login item. Used both as a search filter and, if the item has to be created or updated, as the C(login.username) value.
        required: False
        type: str
'''

EXAMPLES = r'''
- name: 'Get or create a password item from Bitwarden (automated name creation).'
  linuxfabrik.lfops.bitwarden_item:
    hostname: 'appsrv11'
    purpose: 'MariaDB'
    username: 'mariadb-admin'
  register: creds

- name: 'Add a password to the above item'
  linuxfabrik.lfops.bitwarden_item:
    hostname: 'appsrv11'
    purpose: 'MariaDB'
    username: 'mariadb-admin'
    password: 'linuxfabrik'
  register: creds

- debug:
    msg: 'ID: "{{ creds.id }}", Name: "{{ creds.name }}", Username: "{{ creds.username }}", Password: "{{ creds.password }}"'

- name: 'Change name/title of Bitwarden item by using the ID'
  linuxfabrik.lfops.bitwarden_item:
    id: '62b779ca-cb95-4d61-864d-ee670995686a'
    name: 'appsrv133 - New name'
  register: creds

# a full-fledged example
- name: 'Get or create a password item from Bitwarden (automated name creation).'
  linuxfabrik.lfops.bitwarden_item:
    collection_id: '4649ec03-c1be-4d5a-9413-7f7ad8ebbace'
    organization_id: '06c7691f-c64f-4140-8680-d4f60a9cb038'
    hostname: 'appsrv12'
    notes: 'please note'
    purpose: 'MariaDB'
    username: 'mariadb-admin'
    password: 'linuxfabrik'
    uris:
     - 'https://www.example.com'
     - 'https://www.example.org'
  register: creds

- name: 'Set multiple attachments. '
  linuxfabrik.lfops.bitwarden_item:
    hostname: 'appsrv11'
    purpose: 'MariaDB'
    attachments:
      - /tmp/file1
      - /tmp/file2
  register: creds
'''

RETURN = r'''
collectionIds:
    description: List of collection IDs in which the item is.
    type: list
    returned: always
    sample: [ '58a5a2ef-93ca-4ca3-81de-f9b0f2d947a7' ]
favorite:
    description: Whether the item is favorited or not.
    type: bool
    returned: always
    sample: False
folderId:
    description: Bitwarden folder ID in which the item is.
    type: str
    returned: always
    sample: '6fb1792a-dc44-4306-8669-aca5a8bb0e72'
id:
    description: Unique Bitwarden password item ID.
    type: str
    returned: always
    sample: 'daba87c4-44d4-47ee-be7f-f21cb0fc8ea6'
login:
    description: A Bitwarden login object (dictionary).
    returned: always
    type: dict
    contains:
      password:
          description: The password.
          type: str
          returned: always
          sample: '69hFM533bJre2cIO9vXkVnvF1RK5Br'
      passwordRevisionDate:
          description: The last time the password was changed.
          type: str
          returned: always
          sample: '2022-02-23T08:49:21.437Z'
      totp:
          description: TOTP.
          type: str
          returned: always
          sample: 634990
      uris:
          description: A list of Bitwarden URI objects (dictionaries).
          type: complex
          returned: always
          contains:
            match:
                description: Match algorithm.
                type: int
                returned: always
                sample: None
            uri:
                description: The URL.
                type: str
                returned: always
                sample: 'https://www.example.com'
      username:
            description: Username to which the password belongs.
            type: str
            returned: always
            sample: 'root'
name:
    description: Name/Title of the password item.
    type: str
    returned: always
    sample: 'appsrv01 - MariaDB'
notes:
    description: Some notes about the cipher.
    type: str
    returned: always
    sample: 'Automatically generated by Ansible.'
object:
    description: Type of the Bitwarden object. Always returns C(item).
    type: str
    returned: always
    sample: 'item'
organizationId:
    description: The ID of the organization.
    type: str
    returned: always
    sample: '7845ea14-5364-4c62-82ba-383864e47889'
password:
    description: The password. Same as under the C(login) dict, but at a higher level for easier access.
    type: str
    returned: always
    sample: '6VuIkoKQmCl9Yyv3xpgjU6SF2ecs6k'
reprompt:
    description: If Bitwarden should re-prompt for the master password when accessing this item.
    type: int
    returned: always
    sample: 0
revisionDate:
    description: Date/Time the item was created or last modified.
    type: str
    returned: always
    sample: '2019-01-28T15:31:34.300Z'
type:
    description: Bitwarden item type. Always C(1) (login) for items handled by this module. Other Bitwarden types (C(2) secure note, C(3) card, C(4) identity) are filtered out and never returned.
    type: int
    returned: always
    sample: 1
username:
    description: Username to which the password belongs. Same as under the C(login) dict, but at a higher level for easier access.
    type: str
    returned: always
    sample: 'root'
'''

import os

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.linuxfabrik.lfops.plugins.module_utils.bitwarden import \
    Bitwarden


def diff_and_update(current, target):
    """Diffs the current item with the target item and checks if there are relevant changes.
    Returns (changed, updated_item). The updated_item can be sent to `bw` to update the remote item.
    """

    def check_dict_for_changes(current, target):
        changed = False
        for key, value in target.items():
            if isinstance(value, dict):
                if check_dict_for_changes(current.get(key, {}), value):
                    changed = True

            elif (value != current.get(key)) \
                and not (not value and not current.get(key)): # compare None to empty lists and empty strings
                changed = True

        return changed

    # take over id
    target['id'] = current.get('id')

    changed = check_dict_for_changes(current, target)

    return (changed, target)


def run_module():
    # define available arguments/parameters a user can pass to this module
    module_args = dict(
        attachments=dict(type='list', required=False, default=[]),
        collection_id=dict(type='str', required=False, default=None),
        folder_id=dict(type='str', required=False, default=None),
        hostname=dict(type='str', required=False, default=None),
        id=dict(type='str', required=False, default=None),
        name=dict(type='str', required=False, default=None),
        notes=dict(type='str', required=False, default='Generated by Ansible.'),
        organization_id=dict(type='str', required=False, default=None),
        password=dict(type='str', required=False, default=None, no_log=False), # if we set it to True, the passwords in the RETURN values are masked too. see https://github.com/ansible/ansible/issues/71789
        purpose=dict(type='str', required=False, default=None),
        uris=dict(type='list', required=False, default=None),
        username=dict(type='str', required=False, default=None),
    )

    # the AnsibleModule object will be our abstraction working with Ansible
    # this includes instantiation, a couple of common attr would be the
    # args/params passed to the execution, as well as if this module
    # supports check mode
    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    attachments = module.params['attachments']
    if attachments:
        basenames = [os.path.basename(attachment) for attachment in attachments]
        if len(set(basenames)) < len(basenames):
            module.fail_json(msg='This module cannot handle multiple attachments with the same basename.')

        for attachment in attachments:
            if not os.access(attachment, os.R_OK):
                module.fail_json(msg=f'Could not read the attachments at "{attachment}".')

    # extract the variables to make the code more readable
    collection_id = module.params['collection_id']
    folder_id = module.params['folder_id']
    hostname = module.params['hostname']
    item_id = module.params['id']
    name = module.params['name']
    notes = module.params['notes']
    organization_id = module.params['organization_id']
    password = module.params['password']
    purpose = module.params['purpose']
    uris = module.params['uris']
    username = module.params['username']

    bw = Bitwarden()

    if not bw.is_unlocked:
        module.fail_json(msg='Not logged into Bitwarden, or Bitwarden Vault is locked. Please run `bw login` and `bw unlock` first.')

    # to be sure we are up to date
    bw.sync()

    changed = False
    if item_id:
        current_item = bw.get_item_by_id(item_id)
    else:
        name = Bitwarden.get_pretty_name(name, hostname, purpose)
        current_items = bw.get_items(name, username, folder_id, collection_id, organization_id)

        if len(current_items) > 1:
            module.fail_json(msg='Found multiple Bitwarden items with the same name/title and username, cannot decide which one to use. Aborting.')

        current_item = current_items[0] if current_items else None

    login_uris = bw.get_template_item_login_uri(uris)
    login = bw.get_template_item_login(username, password, login_uris)
    target_item = bw.get_template_item(
        name,
        login,
        notes,
        organization_id,
        collection_id,
        folder_id,
    )

    # A None password means "do not manage the password": preserve the existing
    # item's password instead of overwriting it with null.
    if password is None and current_item and current_item.get('login'):
        target_item['login']['password'] = current_item['login'].get('password')

    if current_item:
        # check if changed, adjust if necessary
        changed, updated_item = diff_and_update(current_item, target_item)
        if changed and not module.check_mode:
            result = bw.edit_item(updated_item, updated_item['id'])
        elif changed:
            result = updated_item
        else:
            result = current_item

    else:
        # generate a new one
        changed = True
        result = target_item if module.check_mode else bw.create_item(target_item)

    if attachments:
        current_attachments = set(current_attachment['fileName'] for current_attachment in result.get('attachments', []))
        attachments_changed = False
        for attachment in attachments:
            if os.path.basename(attachment) not in current_attachments:
                attachments_changed = True
                if not module.check_mode:
                    bw.add_attachment(result['id'], attachment)

        if attachments_changed:
            changed = True
            # we need to fetch the item again, so that it also contains the newly added attachments
            if not module.check_mode:
                result = bw.get_item_by_id(result['id'])

    result['changed'] = changed
    # move username and password higher for easier access
    result['username'] = result['login']['username']
    result['password'] = result['login']['password']
    module.exit_json(**result)


def main():
    run_module()


if __name__ == '__main__':
    main()
