#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
module: gpg_key

short_description: Find or create a GPG private key

description:
    - Ensures that a GPG private key matching the given attributes exists on the host. Lists all secret keys via C(gpg) and matches them against the supplied options. If a matching key is found, it is returned as is; otherwise a new one is generated.
    - The C(uid) of an existing key is parsed back into its C(name_real), C(name_comment) and C(name_email) parts and compared against the parameters; key type, key length and (if present) subkey type and subkey length must match as well.
    - When the key has subkeys, at least one subkey must match I(subkey_type) and I(subkey_length); GPG's unattended generator can only create a single subkey per key but more can be added later, hence the partial match.
    - The passphrase is never used to decide whether a key matches, since it is not visible in the secret key listing.
    - On success, the module returns the matched or newly generated key (the same dict shape as L(python-gnupg's list_keys(),https://gnupg.readthedocs.io/en/latest/#listing-keys)) plus the ASCII-armored exports of the private and public key.
    - Internally relies on U(https://github.com/vsajip/python-gnupg).

notes:
    - Only a small subset of the available GPG options is exposed (single name/email/comment, key type, key length, optional one subkey, optional passphrase). Issues and pull requests for additional options are welcome.
    - If multiple keys match the supplied options, the module fails because it cannot decide which one to return.
    - In check mode, the module reports C(changed=true) when no matching key is found, but it does not generate one.

requirements:
    - GNU Privacy Guard command line tool C(gpg) on the host where the module runs.
    - "No separate C(python-gnupg) install is required: a copy of the library is bundled with the collection and shipped together with the module."

author:
    - Linuxfabrik GmbH, Zurich, Switzerland, https://www.linuxfabrik.ch

version_added: "1.0.0"

options:
    gnupghome:
        description: Path to the GnuPG home directory. When unset, falls back to whatever C(gpg) itself uses (typically C($HOME/.gnupg)). The directory is created with mode C(0o700) if it does not exist.
        required: False
        type: path
    gpgbinary:
        description: Name of, or path to, the C(gpg) executable.
        required: False
        type: str
        default: 'gpg'
    key_length:
        description: Key length in bits. Used both as a match criterion against existing keys and as the bit length for newly generated keys.
        required: False
        type: int
        default: 1024
    key_type:
        description: Key algorithm. Used both as a match criterion (compared against the human-readable algorithm name C(RSA), C(DSA), C(Elgamal), C(ECDH), C(ECDSA)) and as the algorithm for newly generated keys.
        required: False
        type: str
        default: 'RSA'
    name_comment:
        description: Comment portion of the GPG user ID (the text in parentheses).
        required: False
        type: str
        default: 'Generated by Ansible.'
    name_email:
        description: Email portion of the GPG user ID (the text in angle brackets).
        required: False
        type: str
        default: 'info@example.com'
    name_real:
        description: Real-name portion of the GPG user ID (the text before the comment / email).
        required: False
        type: str
        default: 'Autogenerated Key'
    passphrase:
        description: Passphrase for the secret key. When empty (the default), the generated key is unprotected (C(no_protection)). Never used to decide whether an existing key matches.
        required: False
        type: str
    subkey_length:
        description: Length in bits of the (single) subkey to generate, and to match against existing subkeys. Only meaningful together with I(subkey_type).
        required: False
        type: int
    subkey_type:
        description: Algorithm of the (single) subkey to generate, and to match against existing subkeys. Only meaningful together with I(subkey_length).
        required: False
        type: str
'''

EXAMPLES = r'''
- name: 'Generate a GPG key by using the defaults'
  linuxfabrik.lfops.gpg_key:
  register: gpg_key

- ansible.builtin.debug:
    var: gpg_key

- name: 'Generate gpg key'
  linuxfabrik.lfops.gpg_key:
    name_real: 'My name'
    name_email: '{{ ansible_facts["user_id"] }}@{{ ansible_facts["nodename"] }}'
    key_type: 'RSA'
    key_length: 4096
    passphrase: 'secret-passphrase'
    subkey_type: 'RSA'
    subkey_length: 4096
  register: gpg_key
'''

RETURN = r'''
ascii_armored_private_key:
    description: ASCII-armored export of the private key.
    returned: success
    type: str
    sample: '-----BEGIN PGP PRIVATE KEY BLOCK-----\n\n...\n-----END PGP PRIVATE KEY BLOCK-----\n'
ascii_armored_public_key:
    description: ASCII-armored export of the public key.
    returned: success
    type: str
    sample: '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\n...\n-----END PGP PUBLIC KEY BLOCK-----\n'
key:
    description: The matched or newly generated GPG key, in the dict shape returned by python-gnupg's L(list_keys(),https://gnupg.readthedocs.io/en/latest/#listing-keys).
    returned: success
    type: dict
    contains:
        algo:
            description: Public key algorithm number (IANA PGP-parameters; 1/2/3 = RSA, 16 = Elgamal, 17 = DSA, 18 = ECDH, 19 = ECDSA).
            returned: success
            type: int
            sample: 1
        cap:
            description: Key capabilities (encrypt/sign/certify/authenticate). Uppercase letters indicate the primary key, lowercase the subkeys.
            returned: success
            type: str
            sample: escaESCA
        compliance:
            description: Compliance flags reported by GPG (e.g. C(8) for OpenPGP, C(23) for FIPS).
            returned: success
            type: str
            sample: ''
        curve:
            description: Curve name for elliptic curve cryptography (ECC) keys. Empty for RSA/DSA/Elgamal.
            returned: success
            type: str
            sample: ''
        date:
            description: Creation date of the key in UTC as a Unix timestamp.
            returned: success
            type: int
            sample: 1645019144
        dummy:
            description: Certificate serial number, UID hash or trust signature info.
            returned: success
            type: str
            sample: ''
        expires:
            description: Expiry date of the key in UTC as a Unix timestamp, or empty if the key does not expire.
            returned: success
            type: str
            sample: ''
        fingerprint:
            description: Full key fingerprint.
            returned: success
            type: str
            sample: ECA3505F5A6F61A528D6A5087EFF958551A5481E
        flag:
            description: Flag field as reported by GPG. Reserved; usually empty.
            returned: success
            type: str
            sample: ''
        hash:
            description: Hash algorithm used by the key.
            returned: success
            type: str
            sample: ''
        issuer:
            description: Issuer information (only set on signature records).
            returned: success
            type: str
            sample: ''
        keyid:
            description: Short (16-character) key ID.
            returned: success
            type: str
            sample: 7EFF958551A5481E
        length:
            description: Key length in bits.
            returned: success
            type: int
            sample: 1024
        origin:
            description: Origin of the key as reported by GPG.
            returned: success
            type: int
            sample: 0
        ownertrust:
            description: Owner trust level (C(u) ultimate, C(f) full, C(m) marginal, C(n) never, C(-) unknown).
            returned: success
            type: str
            sample: u
        sig:
            description: Signature class (only set on signature records).
            returned: success
            type: str
            sample: ''
        subkey_info:
            description: Dictionary of subkey records keyed by subkey ID. Each record has the same shape as the parent key record.
            returned: success
            type: dict
        subkeys:
            description: List of C([keyid, type]) entries for each subkey.
            returned: success
            type: list
            sample:
                - 524C9D5EB862A934
                - null
                - D002B0EB3BF40CF209930E74524C9D5EB862A934
        token:
            description: Smartcard / token serial number, or C(+) when the key is on a token without a readable serial.
            returned: success
            type: str
            sample: +
        trust:
            description: Key validity (C(u) ultimate, C(f) full, C(m) marginal, C(n) never, C(-) unknown, C(e) expired).
            returned: success
            type: str
            sample: u
        type:
            description: Record type (C(sec) secret primary key, C(pub) public primary key, C(ssb)/C(sub) subkey).
            returned: success
            type: str
            sample: sec
        uids:
            description: List of user IDs attached to the key.
            returned: success
            type: list
            sample: ['Autogenerated Key (Generated by Ansible.) <info@example.com>']
        updated:
            description: Last update timestamp.
            returned: success
            type: str
            sample: ''
'''

import logging
import os
import re
import traceback

from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.common.text.converters import to_native

from ansible_collections.linuxfabrik.lfops.plugins.module_utils.gnupg import GPG

logger = logging.getLogger('gnupg')
logger.setLevel(logging.DEBUG)

# taken from https://www.iana.org/assignments/pgp-parameters/pgp-parameters.xhtml#pgp-parameters-12
algo_ids = {
    1: 'RSA',
    2: 'RSA',
    3: 'RSA',
    16: 'Elgamal',
    17: 'DSA',
    18: 'ECDH',
    19: 'ECDSA',
}

name_email_regex = re.compile(r' <(.*)>$')
name_comment_regex = re.compile(r' \((.*)\)')


def match_key(key, params):
    if algo_ids.get(int(key['algo']), 'Unknown') != params['key_type']:
        return False

    if int(key['length']) != params['key_length']:
        return False

    # we assume that there can only be one uid, as we couldn't find anything contradicting that
    uid = key['uids'][0].strip()
    name_real_end = len(uid)

    name_email_match = name_email_regex.search(uid)
    name_email = None
    if name_email_match:
        name_email = name_email_match.group(1)
        name_real_end = name_email_match.start()

    if name_email != params['name_email']:
        return False

    name_comment_match = name_comment_regex.search(uid)
    name_comment = None
    if name_comment_match:
        name_comment = name_comment_match.group(1)
        name_real_end = name_comment_match.start()

    if name_comment != params['name_comment']:
        return False

    name_real = uid[:name_real_end]

    if name_real != params['name_real']:
        return False

    if 'subkey_info' in key:
        # if there is at least one matching subkey, we assume a match. the unattended creation can only create a single subkey,
        # howerever, it is possible to add another one manually later.
        first_subkey_match = None
        for subkey_id, subkey in key['subkey_info'].items():

            if algo_ids.get(int(subkey['algo']), 'Unknown') != params['subkey_type']:
                continue

            if int(subkey['length']) != params['subkey_length']:
                continue

            first_subkey_match = subkey

        if not first_subkey_match:
            return False

    return True


def add_armored_exports_and_exit(gpg, module, result):
    ascii_armored_private_key = gpg.export_keys(result['key']['fingerprint'], secret=True, passphrase=module.params['passphrase'])
    if not ascii_armored_private_key:
        # sadly, we do not get more information from the library
        module.fail_json(msg='Failed to export armored private key. Is the passphrase correct?', **result)
    result['ascii_armored_private_key'] = ascii_armored_private_key

    ascii_armored_public_key = gpg.export_keys(result['key']['fingerprint'], passphrase=module.params['passphrase'])
    result['ascii_armored_public_key'] = ascii_armored_public_key
    module.exit_json(**result)


def run_module():
    # define available arguments/parameters a user can pass to the module
    module_args = dict(
        gpgbinary=dict(type='str', required=False, default='gpg'),
        gnupghome=dict(type='path', required=False),

        name_real=dict(type='str', required=False, default='Autogenerated Key'),
        name_comment=dict(type='str', required=False, default='Generated by Ansible.'),
        name_email=dict(type='str', required=False, default='info@example.com'),

        key_type=dict(type='str', required=False, default='RSA'),
        key_length=dict(type='int', required=False, default=1024),

        passphrase=dict(type='str', required=False, default='', no_log=True),

        subkey_type=dict(type='str', required=False),
        subkey_length=dict(type='int', required=False),
    )

    result = dict(
        changed=False,
        key=None,
    )

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    gnupghome = module.params['gnupghome']
    if gnupghome and not os.path.isdir(gnupghome):

        if module.check_mode:
            # since there is no directory, there are no keys - meaning we have to generate one for sure. set to changed but do not do anything
            result['changed'] = True
            module.exit_json(**result)

        os.makedirs(gnupghome, 0o700)

    try:
        gpg = GPG(
            gpgbinary=module.params['gpgbinary'],
            gnupghome=gnupghome,
        )
    except (OSError, ValueError) as e:
        module.fail_json(msg=f'There was an error executing gpg: {to_native(e)}', exception=traceback.format_exc(), **result)

    # use whatever logic you need to determine whether or not this module
    # made any modifications to your target

    keys = gpg.list_keys(secret=True)
    if keys.returncode != 0:
        module.fail_json(msg='Failed to list current keys.', rc=keys.returncode, stdout=keys.data, stderr=keys.stderr, **result)

    # do match on all given arguments except for passphrase (as we do not see that one).
    match = None
    for key in keys:
        matched = match_key(key, module.params)
        if matched:
            if match is None:
                match = key
            else:
                module.fail_json(msg='Found multiple keys with the same attributes, cannot decide which one to use. Aborting.', **result)

    if match:
        result['key'] = match
        add_armored_exports_and_exit(gpg, module, result)
    else:
        # set changed before quitting in check mode to indicate that we would generate a new key
        result['changed'] = True

    # if the user is working with this module in only check mode we do not
    # want to make any changes to the environment, just return the current
    # state with no modifications
    if module.check_mode:
        module.exit_json(**result)

    # manipulate or modify the state as needed (this is going to be the
    # part where your module will do what it needs to do)
    params = {k: v for k, v in module.params.items() if v is not None}
    params.pop('gnupghome', None) # provide default to prevent KeyError
    params.pop('gpgbinary', None) # provide default to prevent KeyError
    if not module.params['passphrase']:
        params['no_protection'] = True

    input_data = gpg.gen_key_input(**params)
    new_key = gpg.gen_key(input_data)
    if not new_key:
        # do not echo input_data here: it contains the cleartext passphrase
        module.fail_json(msg='Failed to generate a new key.', rc=new_key.returncode, stdout=new_key.data, stderr=new_key.stderr, **result)

    # list the keys again, as we only got the fingerprint from gen_key()
    keys = gpg.list_keys(secret=True)
    if keys.returncode != 0:
        module.fail_json(msg='Failed to list current keys.', rc=keys.returncode, stdout=keys.data, stderr=keys.stderr, **result)

    for key in keys:
        if key['fingerprint'] == new_key.fingerprint:
            result['key'] = key
            break

    if not result['key']:
        module.fail_json(msg='Could not find the newly generated key.', **result)

    # in the event of a successful module execution, you will want to
    # simple AnsibleModule.exit_json(), passing the key/value results
    add_armored_exports_and_exit(gpg, module, result)


def main():
    run_module()


if __name__ == '__main__':
    main()
