name: 'Linuxfabrik: Release'

on:
  push:
    tags:
      - 'v*'

# modify the default permissions granted to the GITHUB_TOKEN
permissions: 'read-all'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write' # to push to the repo and create the release

    steps:

      - name: 'Harden the runner (Audit all outbound calls)'
        uses: 'step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920' # v2.20.0
        with:
          egress-policy: 'audit'

      - name: 'Create GitHub Release for ${{ github.ref_name }}'
        uses: 'softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228' # v3.0.2
        with:
          tag_name: '${{ github.ref_name }}'
          body: |
            Release Notes/CHANGELOG at https://github.com/Linuxfabrik/lfops/blob/main/CHANGELOG.md
          prerelease: false
