name: 'Linuxfabrik: Release'

on:
  push:
    tags:
      - 'v*'

# modify the default permissions granted to the GITHUB_TOKEN
permissions: 'read-all'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write' # to push to the repo and create the release

    steps:

      - name: 'Harden the runner (Audit all outbound calls)'
        uses: 'step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176' # v2.17.0
        with:
          egress-policy: 'audit'

      - name: 'Create GitHub Release for ${{ github.ref_name }}'
        uses: 'softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe' # v2.6.1
        with:
          tag_name: '${{ github.ref_name }}'
          body: |
            Release Notes/CHANGELOG at https://github.com/Linuxfabrik/lfops/blob/main/CHANGELOG.md
          prerelease: false
