name: 'Linuxfabrik: Update pre-commit hooks'

on:
  schedule:
    - cron: '0 5 * * 5'
  workflow_dispatch: {}

permissions: 'read-all'

jobs:
  update:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Harden the runner (Audit all outbound calls)'
        uses: 'step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920' # v2.20.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7.0.1

      - name: 'Set up Python'
        uses: 'actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97' # v7.0.0
        with:
          python-version: '3.12'

      - name: 'Install pre-commit'
        run: 'pip install --require-hashes --requirement .github/pre-commit/requirements.txt'

      - name: 'Run pre-commit autoupdate'
        run: 'pre-commit autoupdate'

      - name: 'Create Pull Request'
        uses: 'peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1' # v8.1.1
        with:
          commit-message: 'chore: update pre-commit hooks'
          title: 'chore: update pre-commit hooks'
          body: 'Automatic pre-commit hook version update.'
          branch: 'chore/pre-commit-autoupdate'
