__icingaweb2__php__modules__dependent_var:
  Debian:
    - name: 'php-bz2'
      state: 'present'
    - name: 'php-curl'
      state: 'present'
    - name: 'php-intl'
      state: 'present'
    - name: 'php-mbstring'
      state: 'present'
    - name: 'php-imagick'
      state: 'present'
    - name: 'php-xml'
      state: 'present'
  RedHat:
    - name: 'php-curl'
      state: 'present'
    - name: 'php-intl'
      state: 'present'
    - name: 'php-mbstring'
      state: 'present'
    - name: 'php-pecl-imagick'
      state: 'present'
    - name: 'php-process'
      state: 'present'
    - name: 'php-xml'
      state: 'present'
icingaweb2__php__modules__dependent_var: '{{
    __icingaweb2__php__modules__dependent_var
    | linuxfabrik.lfops.platform_select(ansible_facts)
  }}'
